# Generated by Django 2.2.2 on 2019-11-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedCep',
            fields=[
                ('cep', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='CEP')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('city', models.CharField(max_length=128, verbose_name='City')),
                ('neighborhood', models.CharField(max_length=128, null=True, verbose_name='Neighborhood')),
                ('street', models.CharField(max_length=128, null=True, verbose_name='Address')),
                ('provider', models.CharField(max_length=128, verbose_name='Provider')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
