# Generated by Django 2.2.2 on 2019-11-20 20:10

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CepCache",
            fields=[
                (
                    "cep",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="CEP",
                    ),
                ),
                ("state", models.CharField(max_length=2, verbose_name="State")),
                ("city", models.CharField(max_length=128, verbose_name="City")),
                (
                    "district",
                    models.CharField(
                        max_length=128, null=True, verbose_name="District"
                    ),
                ),
                (
                    "street",
                    models.CharField(max_length=128, null=True, verbose_name="Address"),
                ),
                ("provider", models.CharField(max_length=128, verbose_name="Provider")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated at"
                    ),
                ),
            ],
            managers=[("valid_ceps", django.db.models.manager.Manager()),],
        ),
    ]
