# Generated by Django 2.2.2 on 2019-06-03 20:47

from django.db import migrations

from simplecep.loader import load_base_ceps


def populate_ceps(apps, schema_editor):
    Cep = apps.get_model("simplecep", "Cep")
    load_base_ceps(Cep)


class Migration(migrations.Migration):
    dependencies = [("simplecep", "0001_initial")]
    operations = [migrations.RunPython(populate_ceps)]
