# Generated by Django 2.2.2 on 2019-06-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cep',
            fields=[
                ('cep', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='CEP')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('city', models.CharField(max_length=128, verbose_name='City')),
                ('district', models.CharField(max_length=128, null=True, verbose_name='District')),
                ('address', models.CharField(max_length=128, null=True, verbose_name='Address')),
                ('number', models.CharField(max_length=64, null=True, verbose_name='Number')),
                ('extra', models.CharField(max_length=128, null=True, verbose_name='Extra')),
            ],
        ),
    ]
