# Generated by Django 2.2.2 on 2019-06-03 20:47
import sys

from django.db import migrations

from django_fast_cep.loader import load_base_ceps


def populate_ceps(apps, schema_editor):
    Cep = apps.get_model("django_fast_cep", "Cep")
    load_base_ceps(Cep)


class Migration(migrations.Migration):

    dependencies = [("django_fast_cep", "0001_initial")]

    operations = [migrations.RunPython(populate_ceps)]
