# This file was generated by the "capture_real_responses.py" script.
# On Wed, 20 Nov 2019 17:22:33 +0000.
#
# To update it run:
# python -m tests.providers.capture_real_responses

captured_responses = [
    {
        "request": {
            "full_url": "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente",
            "method": "POST",
            "headers": {},
            "data": bytearray(
                b'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cli="http://cliente.bean.master.sigep.bsb.correios.com.br/">\n               <soapenv:Header/>\n               <soapenv:Body>\n                  <cli:consultaCEP>\n                     <cep>01001000</cep>\n                  </cli:consultaCEP>\n               </soapenv:Body>\n            </soapenv:Envelope>'
            ),
        },
        "response": {
            "type": "success",
            "data": b'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:consultaCEPResponse xmlns:ns2="http://cliente.bean.master.sigep.bsb.correios.com.br/"><return><bairro>S\xe9</bairro><cep>01001000</cep><cidade>S\xe3o Paulo</cidade><complemento2>- lado \xedmpar</complemento2><end>Pra\xe7a da S\xe9</end><uf>SP</uf></return></ns2:consultaCEPResponse></soap:Body></soap:Envelope>',
        },
    },
    {
        "request": {
            "full_url": "http://cep.republicavirtual.com.br/web_cep.php?cep=01001000&formato=json",
            "method": "GET",
            "headers": {"Accept": "application/json"},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{"resultado":"1","resultado_txt":"sucesso - cep completo","uf":"SP","cidade":"S\\u00e3o Paulo","bairro":"S\\u00e9","tipo_logradouro":"Pra\\u00e7a","logradouro":"da S\\u00e9"}',
        },
    },
    {
        "request": {
            "full_url": "https://viacep.com.br/ws/01001000/json/unicode/",
            "method": "GET",
            "headers": {},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{\n  "cep": "01001-000",\n  "logradouro": "Pra\\u00e7a da S\\u00e9",\n  "complemento": "lado \\u00edmpar",\n  "bairro": "S\\u00e9",\n  "localidade": "S\\u00e3o Paulo",\n  "uf": "SP",\n  "unidade": "",\n  "ibge": "3550308",\n  "gia": "1004"\n}',
        },
    },
    {
        "request": {
            "full_url": "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente",
            "method": "POST",
            "headers": {},
            "data": bytearray(
                b'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cli="http://cliente.bean.master.sigep.bsb.correios.com.br/">\n               <soapenv:Header/>\n               <soapenv:Body>\n                  <cli:consultaCEP>\n                     <cep>57010240</cep>\n                  </cli:consultaCEP>\n               </soapenv:Body>\n            </soapenv:Envelope>'
            ),
        },
        "response": {
            "type": "success",
            "data": b'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:consultaCEPResponse xmlns:ns2="http://cliente.bean.master.sigep.bsb.correios.com.br/"><return><bairro>Prado</bairro><cep>57010240</cep><cidade>Macei\xf3</cidade><complemento2></complemento2><end>Rua Desembargador Inoc\xeancio Lins</end><uf>AL</uf></return></ns2:consultaCEPResponse></soap:Body></soap:Envelope>',
        },
    },
    {
        "request": {
            "full_url": "http://cep.republicavirtual.com.br/web_cep.php?cep=57010240&formato=json",
            "method": "GET",
            "headers": {"Accept": "application/json"},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{"resultado":"1","resultado_txt":"sucesso - cep completo","uf":"AL","cidade":"Macei\\u00f3","bairro":"Prado","tipo_logradouro":"Rua","logradouro":"Desembargador Inoc\\u00eancio Lins"}',
        },
    },
    {
        "request": {
            "full_url": "https://viacep.com.br/ws/57010240/json/unicode/",
            "method": "GET",
            "headers": {},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{\n  "cep": "57010-240",\n  "logradouro": "Rua Desembargador Inoc\\u00eancio Lins",\n  "complemento": "",\n  "bairro": "Prado",\n  "localidade": "Macei\\u00f3",\n  "uf": "AL",\n  "unidade": "",\n  "ibge": "2704302",\n  "gia": ""\n}',
        },
    },
    {
        "request": {
            "full_url": "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente",
            "method": "POST",
            "headers": {},
            "data": bytearray(
                b'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cli="http://cliente.bean.master.sigep.bsb.correios.com.br/">\n               <soapenv:Header/>\n               <soapenv:Body>\n                  <cli:consultaCEP>\n                     <cep>18170000</cep>\n                  </cli:consultaCEP>\n               </soapenv:Body>\n            </soapenv:Envelope>'
            ),
        },
        "response": {
            "type": "success",
            "data": b'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:consultaCEPResponse xmlns:ns2="http://cliente.bean.master.sigep.bsb.correios.com.br/"><return><bairro></bairro><cep>18170000</cep><cidade>Piedade</cidade><complemento2></complemento2><end></end><uf>SP</uf></return></ns2:consultaCEPResponse></soap:Body></soap:Envelope>',
        },
    },
    {
        "request": {
            "full_url": "http://cep.republicavirtual.com.br/web_cep.php?cep=18170000&formato=json",
            "method": "GET",
            "headers": {"Accept": "application/json"},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{"resultado":"2","resultado_txt":"sucesso - cep \\u00fanico","uf":"SP","cidade":"Piedade","bairro":"","tipo_logradouro":"","logradouro":"","debug":" - encontrado via search_db cep unico - "}',
        },
    },
    {
        "request": {
            "full_url": "https://viacep.com.br/ws/18170000/json/unicode/",
            "method": "GET",
            "headers": {},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{\n  "cep": "18170-000",\n  "logradouro": "",\n  "complemento": "",\n  "bairro": "",\n  "localidade": "Piedade",\n  "uf": "SP",\n  "unidade": "",\n  "ibge": "3537800",\n  "gia": "5265"\n}',
        },
    },
    {
        "request": {
            "full_url": "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente",
            "method": "POST",
            "headers": {},
            "data": bytearray(
                b'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cli="http://cliente.bean.master.sigep.bsb.correios.com.br/">\n               <soapenv:Header/>\n               <soapenv:Body>\n                  <cli:consultaCEP>\n                     <cep>78175000</cep>\n                  </cli:consultaCEP>\n               </soapenv:Body>\n            </soapenv:Envelope>'
            ),
        },
        "response": {
            "type": "success",
            "data": b'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:consultaCEPResponse xmlns:ns2="http://cliente.bean.master.sigep.bsb.correios.com.br/"><return><bairro></bairro><cep>78175000</cep><cidade>Pocon\xe9</cidade><complemento2></complemento2><end></end><uf>MT</uf></return></ns2:consultaCEPResponse></soap:Body></soap:Envelope>',
        },
    },
    {
        "request": {
            "full_url": "http://cep.republicavirtual.com.br/web_cep.php?cep=78175000&formato=json",
            "method": "GET",
            "headers": {"Accept": "application/json"},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{"resultado":"2","resultado_txt":"sucesso - cep \\u00fanico","uf":"MT","cidade":"Pocon\\u00e9","bairro":"","tipo_logradouro":"","logradouro":"","debug":" - encontrado via search_db cep unico - "}',
        },
    },
    {
        "request": {
            "full_url": "https://viacep.com.br/ws/78175000/json/unicode/",
            "method": "GET",
            "headers": {},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{\n  "cep": "78175-000",\n  "logradouro": "",\n  "complemento": "",\n  "bairro": "",\n  "localidade": "Pocon\\u00e9",\n  "uf": "MT",\n  "unidade": "",\n  "ibge": "5106505",\n  "gia": ""\n}',
        },
    },
    {
        "request": {
            "full_url": "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente",
            "method": "POST",
            "headers": {},
            "data": bytearray(
                b'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cli="http://cliente.bean.master.sigep.bsb.correios.com.br/">\n               <soapenv:Header/>\n               <soapenv:Body>\n                  <cli:consultaCEP>\n                     <cep>63200970</cep>\n                  </cli:consultaCEP>\n               </soapenv:Body>\n            </soapenv:Envelope>'
            ),
        },
        "response": {
            "type": "success",
            "data": b'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:consultaCEPResponse xmlns:ns2="http://cliente.bean.master.sigep.bsb.correios.com.br/"><return><bairro>Centro</bairro><cep>63200970</cep><cidade>Miss\xe3o Velha</cidade><complemento2></complemento2><end>Rua Jos\xe9 Sobreira da Cruz 271</end><uf>CE</uf></return></ns2:consultaCEPResponse></soap:Body></soap:Envelope>',
        },
    },
    {
        "request": {
            "full_url": "http://cep.republicavirtual.com.br/web_cep.php?cep=63200970&formato=json",
            "method": "GET",
            "headers": {"Accept": "application/json"},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{"debug":" - nao encontrado via search_db cep unico - ","resultado":"1","resultado_txt":"sucesso - cep completo","uf":"CE","cidade":"Miss\\u00e3o Velha","bairro":"Centro\\u00a0","tipo_logradouro":"Rua","logradouro":"Jos\\u00e9 Sobreira da Cruz, 271 "}',
        },
    },
    {
        "request": {
            "full_url": "https://viacep.com.br/ws/63200970/json/unicode/",
            "method": "GET",
            "headers": {},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{\n  "cep": "63200-970",\n  "logradouro": "Rua Jos\\u00e9 Sobreira da Cruz 271",\n  "complemento": "",\n  "bairro": "Centro",\n  "localidade": "Miss\\u00e3o Velha",\n  "uf": "CE",\n  "unidade": "",\n  "ibge": "2308401",\n  "gia": ""\n}',
        },
    },
    {
        "request": {
            "full_url": "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente",
            "method": "POST",
            "headers": {},
            "data": bytearray(
                b'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cli="http://cliente.bean.master.sigep.bsb.correios.com.br/">\n               <soapenv:Header/>\n               <soapenv:Body>\n                  <cli:consultaCEP>\n                     <cep>69096970</cep>\n                  </cli:consultaCEP>\n               </soapenv:Body>\n            </soapenv:Envelope>'
            ),
        },
        "response": {
            "type": "success",
            "data": b'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:consultaCEPResponse xmlns:ns2="http://cliente.bean.master.sigep.bsb.correios.com.br/"><return><bairro>Cidade Nova</bairro><cep>69096970</cep><cidade>Manaus</cidade><complemento2></complemento2><end>Avenida Noel Nutels 1350</end><uf>AM</uf></return></ns2:consultaCEPResponse></soap:Body></soap:Envelope>',
        },
    },
    {
        "request": {
            "full_url": "http://cep.republicavirtual.com.br/web_cep.php?cep=69096970&formato=json",
            "method": "GET",
            "headers": {"Accept": "application/json"},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{"debug":" - nao encontrado via search_db cep unico - ","resultado":"1","resultado_txt":"sucesso - cep completo","uf":"AM","cidade":"Manaus","bairro":"Cidade Nova\\u00a0","tipo_logradouro":"Avenida","logradouro":"Noel Nutels, 1350 "}',
        },
    },
    {
        "request": {
            "full_url": "https://viacep.com.br/ws/69096970/json/unicode/",
            "method": "GET",
            "headers": {},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{\n  "cep": "69096-970",\n  "logradouro": "Avenida Noel Nutels 1350",\n  "complemento": "",\n  "bairro": "Cidade Nova",\n  "localidade": "Manaus",\n  "uf": "AM",\n  "unidade": "",\n  "ibge": "1302603",\n  "gia": ""\n}',
        },
    },
    {
        "request": {
            "full_url": "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente",
            "method": "POST",
            "headers": {},
            "data": bytearray(
                b'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cli="http://cliente.bean.master.sigep.bsb.correios.com.br/">\n               <soapenv:Header/>\n               <soapenv:Body>\n                  <cli:consultaCEP>\n                     <cep>20010974</cep>\n                  </cli:consultaCEP>\n               </soapenv:Body>\n            </soapenv:Envelope>'
            ),
        },
        "response": {
            "type": "success",
            "data": b'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:consultaCEPResponse xmlns:ns2="http://cliente.bean.master.sigep.bsb.correios.com.br/"><return><bairro>Centro</bairro><cep>20010974</cep><cidade>Rio de Janeiro</cidade><complemento2></complemento2><end>Rua Primeiro de Mar\xe7o 64</end><uf>RJ</uf></return></ns2:consultaCEPResponse></soap:Body></soap:Envelope>',
        },
    },
    {
        "request": {
            "full_url": "http://cep.republicavirtual.com.br/web_cep.php?cep=20010974&formato=json",
            "method": "GET",
            "headers": {"Accept": "application/json"},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{"debug":" - nao encontrado via search_db cep unico - ","resultado":"1","resultado_txt":"sucesso - cep completo","uf":"RJ","cidade":"Rio de Janeiro","bairro":"Centro\\u00a0","tipo_logradouro":"Rua","logradouro":"Primeiro de Mar\\u00e7o, 64 "}',
        },
    },
    {
        "request": {
            "full_url": "https://viacep.com.br/ws/20010974/json/unicode/",
            "method": "GET",
            "headers": {},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{\n  "cep": "20010-974",\n  "logradouro": "Rua Primeiro de Mar\\u00e7o",\n  "complemento": "64",\n  "bairro": "Centro",\n  "localidade": "Rio de Janeiro",\n  "uf": "RJ",\n  "unidade": "",\n  "ibge": "3304557",\n  "gia": ""\n}',
        },
    },
    {
        "request": {
            "full_url": "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente",
            "method": "POST",
            "headers": {},
            "data": bytearray(
                b'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cli="http://cliente.bean.master.sigep.bsb.correios.com.br/">\n               <soapenv:Header/>\n               <soapenv:Body>\n                  <cli:consultaCEP>\n                     <cep>96010900</cep>\n                  </cli:consultaCEP>\n               </soapenv:Body>\n            </soapenv:Envelope>'
            ),
        },
        "response": {
            "type": "success",
            "data": b'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:consultaCEPResponse xmlns:ns2="http://cliente.bean.master.sigep.bsb.correios.com.br/"><return><bairro>Centro</bairro><cep>96010900</cep><cidade>Pelotas</cidade><complemento2></complemento2><end>Rua Tiradentes 2515</end><uf>RS</uf></return></ns2:consultaCEPResponse></soap:Body></soap:Envelope>',
        },
    },
    {
        "request": {
            "full_url": "http://cep.republicavirtual.com.br/web_cep.php?cep=96010900&formato=json",
            "method": "GET",
            "headers": {"Accept": "application/json"},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{"debug":" - nao encontrado via search_db cep unico - ","resultado":"1","resultado_txt":"sucesso - cep completo","uf":"RS","cidade":"Pelotas","bairro":"Centro\\u00a0","tipo_logradouro":"Rua","logradouro":"Tiradentes, 2515 "}',
        },
    },
    {
        "request": {
            "full_url": "https://viacep.com.br/ws/96010900/json/unicode/",
            "method": "GET",
            "headers": {},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{\n  "cep": "96010-900",\n  "logradouro": "Rua Tiradentes",\n  "complemento": "2515",\n  "bairro": "Centro",\n  "localidade": "Pelotas",\n  "uf": "RS",\n  "unidade": "",\n  "ibge": "4314407",\n  "gia": ""\n}',
        },
    },
    {
        "request": {
            "full_url": "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente",
            "method": "POST",
            "headers": {},
            "data": bytearray(
                b'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cli="http://cliente.bean.master.sigep.bsb.correios.com.br/">\n               <soapenv:Header/>\n               <soapenv:Body>\n                  <cli:consultaCEP>\n                     <cep>38101990</cep>\n                  </cli:consultaCEP>\n               </soapenv:Body>\n            </soapenv:Envelope>'
            ),
        },
        "response": {
            "type": "success",
            "data": b'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:consultaCEPResponse xmlns:ns2="http://cliente.bean.master.sigep.bsb.correios.com.br/"><return><bairro></bairro><cep>38101990</cep><cidade>Baixa (Uberaba)</cidade><complemento2></complemento2><end>Rua Bas\xedlio Eug\xeanio dos Santos</end><uf>MG</uf></return></ns2:consultaCEPResponse></soap:Body></soap:Envelope>',
        },
    },
    {
        "request": {
            "full_url": "http://cep.republicavirtual.com.br/web_cep.php?cep=38101990&formato=json",
            "method": "GET",
            "headers": {"Accept": "application/json"},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{"debug":" - nao encontrado via search_db cep unico - ","resultado":"1","resultado_txt":"sucesso - cep completo","uf":"MG  - Distrito","cidade":"Baixa (Uberaba)","bairro":"\\u00a0","tipo_logradouro":"Rua","logradouro":"Bas\\u00edlio Eug\\u00eanio dos Santos "}',
        },
    },
    {
        "request": {
            "full_url": "https://viacep.com.br/ws/38101990/json/unicode/",
            "method": "GET",
            "headers": {},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{\n  "cep": "38101-990",\n  "logradouro": "Rua Bas\\u00edlio Eug\\u00eanio dos Santos",\n  "complemento": "",\n  "bairro": "Baixa",\n  "localidade": "Uberaba",\n  "uf": "MG",\n  "unidade": "",\n  "ibge": "3170107",\n  "gia": ""\n}',
        },
    },
    {
        "request": {
            "full_url": "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente",
            "method": "POST",
            "headers": {},
            "data": bytearray(
                b'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cli="http://cliente.bean.master.sigep.bsb.correios.com.br/">\n               <soapenv:Header/>\n               <soapenv:Body>\n                  <cli:consultaCEP>\n                     <cep>76840000</cep>\n                  </cli:consultaCEP>\n               </soapenv:Body>\n            </soapenv:Envelope>'
            ),
        },
        "response": {
            "type": "success",
            "data": b'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:consultaCEPResponse xmlns:ns2="http://cliente.bean.master.sigep.bsb.correios.com.br/"><return><bairro></bairro><cep>76840000</cep><cidade>Jaci Paran\xe1 (Porto Velho)</cidade><complemento2></complemento2><end></end><uf>RO</uf></return></ns2:consultaCEPResponse></soap:Body></soap:Envelope>',
        },
    },
    {
        "request": {
            "full_url": "http://cep.republicavirtual.com.br/web_cep.php?cep=76840000&formato=json",
            "method": "GET",
            "headers": {"Accept": "application/json"},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{"debug":" - nao encontrado via search_db cep unico - ","resultado":"2","resultado_txt":"sucesso - cep \\u00fanico","uf":"RO  - Distrito","cidade":"Jaci Paran\\u00e1 (Porto Velho)","bairro":"\\u00a0","tipo_logradouro":"","logradouro":""}',
        },
    },
    {
        "request": {
            "full_url": "https://viacep.com.br/ws/76840000/json/unicode/",
            "method": "GET",
            "headers": {},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{\n  "cep": "76840-000",\n  "logradouro": "",\n  "complemento": "",\n  "bairro": "",\n  "localidade": "Jaci Paran\\u00e1 (Porto Velho)",\n  "uf": "RO",\n  "unidade": "",\n  "ibge": "1100205",\n  "gia": ""\n}',
        },
    },
    {
        "request": {
            "full_url": "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente",
            "method": "POST",
            "headers": {},
            "data": bytearray(
                b'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cli="http://cliente.bean.master.sigep.bsb.correios.com.br/">\n               <soapenv:Header/>\n               <soapenv:Body>\n                  <cli:consultaCEP>\n                     <cep>00000000</cep>\n                  </cli:consultaCEP>\n               </soapenv:Body>\n            </soapenv:Envelope>'
            ),
        },
        "response": {
            "type": "error",
            "status": 500,
            "data": b'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>CEP INV\xc1LIDO</faultstring><detail><ns2:SigepClienteException xmlns:ns2="http://cliente.bean.master.sigep.bsb.correios.com.br/">CEP INV\xc1LIDO</ns2:SigepClienteException></detail></soap:Fault></soap:Body></soap:Envelope>',
        },
    },
    {
        "request": {
            "full_url": "http://cep.republicavirtual.com.br/web_cep.php?cep=00000000&formato=json",
            "method": "GET",
            "headers": {"Accept": "application/json"},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{"debug":" - nao encontrado via search_db cep unico - ","resultado":"0","resultado_txt":"sucesso - cep n\\u00e3o encontrado","uf":"","cidade":"","bairro":"","tipo_logradouro":"","logradouro":""}',
        },
    },
    {
        "request": {
            "full_url": "https://viacep.com.br/ws/00000000/json/unicode/",
            "method": "GET",
            "headers": {},
            "data": None,
        },
        "response": {"type": "success", "data": b'{\n  "erro": true\n}'},
    },
    {
        "request": {
            "full_url": "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente",
            "method": "POST",
            "headers": {},
            "data": bytearray(
                b'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cli="http://cliente.bean.master.sigep.bsb.correios.com.br/">\n               <soapenv:Header/>\n               <soapenv:Body>\n                  <cli:consultaCEP>\n                     <cep>11111111</cep>\n                  </cli:consultaCEP>\n               </soapenv:Body>\n            </soapenv:Envelope>'
            ),
        },
        "response": {
            "type": "error",
            "status": 500,
            "data": b'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>CEP INV\xc1LIDO</faultstring><detail><ns2:SigepClienteException xmlns:ns2="http://cliente.bean.master.sigep.bsb.correios.com.br/">CEP INV\xc1LIDO</ns2:SigepClienteException></detail></soap:Fault></soap:Body></soap:Envelope>',
        },
    },
    {
        "request": {
            "full_url": "http://cep.republicavirtual.com.br/web_cep.php?cep=11111111&formato=json",
            "method": "GET",
            "headers": {"Accept": "application/json"},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{"debug":" - nao encontrado via search_db cep unico - ","resultado":"0","resultado_txt":"sucesso - cep n\\u00e3o encontrado","uf":"","cidade":"","bairro":"","tipo_logradouro":"","logradouro":""}',
        },
    },
    {
        "request": {
            "full_url": "https://viacep.com.br/ws/11111111/json/unicode/",
            "method": "GET",
            "headers": {},
            "data": None,
        },
        "response": {"type": "success", "data": b'{\n  "erro": true\n}'},
    },
    {
        "request": {
            "full_url": "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente",
            "method": "POST",
            "headers": {},
            "data": bytearray(
                b'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cli="http://cliente.bean.master.sigep.bsb.correios.com.br/">\n               <soapenv:Header/>\n               <soapenv:Body>\n                  <cli:consultaCEP>\n                     <cep>99999999</cep>\n                  </cli:consultaCEP>\n               </soapenv:Body>\n            </soapenv:Envelope>'
            ),
        },
        "response": {
            "type": "error",
            "status": 500,
            "data": b'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>CEP INV\xc1LIDO</faultstring><detail><ns2:SigepClienteException xmlns:ns2="http://cliente.bean.master.sigep.bsb.correios.com.br/">CEP INV\xc1LIDO</ns2:SigepClienteException></detail></soap:Fault></soap:Body></soap:Envelope>',
        },
    },
    {
        "request": {
            "full_url": "http://cep.republicavirtual.com.br/web_cep.php?cep=99999999&formato=json",
            "method": "GET",
            "headers": {"Accept": "application/json"},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{"debug":" - nao encontrado via search_db cep unico - ","resultado":"0","resultado_txt":"sucesso - cep n\\u00e3o encontrado","uf":"","cidade":"","bairro":"","tipo_logradouro":"","logradouro":""}',
        },
    },
    {
        "request": {
            "full_url": "https://viacep.com.br/ws/99999999/json/unicode/",
            "method": "GET",
            "headers": {},
            "data": None,
        },
        "response": {"type": "success", "data": b'{\n  "erro": true\n}'},
    },
    {
        "request": {
            "full_url": "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente",
            "method": "POST",
            "headers": {},
            "data": bytearray(
                b'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cli="http://cliente.bean.master.sigep.bsb.correios.com.br/">\n               <soapenv:Header/>\n               <soapenv:Body>\n                  <cli:consultaCEP>\n                     <cep>01111110</cep>\n                  </cli:consultaCEP>\n               </soapenv:Body>\n            </soapenv:Envelope>'
            ),
        },
        "response": {
            "type": "success",
            "data": b'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:consultaCEPResponse xmlns:ns2="http://cliente.bean.master.sigep.bsb.correios.com.br/"/></soap:Body></soap:Envelope>',
        },
    },
    {
        "request": {
            "full_url": "http://cep.republicavirtual.com.br/web_cep.php?cep=01111110&formato=json",
            "method": "GET",
            "headers": {"Accept": "application/json"},
            "data": None,
        },
        "response": {
            "type": "success",
            "data": b'{"debug":" - nao encontrado via search_db cep unico - ","resultado":"0","resultado_txt":"sucesso - cep n\\u00e3o encontrado","uf":"","cidade":"","bairro":"","tipo_logradouro":"","logradouro":""}',
        },
    },
    {
        "request": {
            "full_url": "https://viacep.com.br/ws/01111110/json/unicode/",
            "method": "GET",
            "headers": {},
            "data": None,
        },
        "response": {"type": "success", "data": b'{\n  "erro": true\n}'},
    },
]
